name: build

on: workflow_dispatch

jobs:
  build-job:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout ci
        uses: actions/checkout@v2
        with:
          path: srcroot

      - name: checkout rpi-newer-crosstools
        uses: actions/checkout@v2
        with:
          repository: rvagg/rpi-newer-crosstools
          path: rpi-newer-crosstools

      - name: prepare out directory
        run: mkdir -p out scratch
        shell: bash

      - name: linux packages
        run: sudo apt-get install -y p7zip-full xz-utils
        shell: bash

      - name: bundle gcc 8.3.0
        run: |
          cp ../srcroot/bin/cross x64-gcc-8.3.0/arm-rpi-linux-gnueabihf/bin
          tar -cJf ../out/x64-gcc-8.3.0.tar.xz x64-gcc-8.3.0
        working-directory: rpi-newer-crosstools
        shell: bash

      - name: SDL2.framework
        run: |
          wget https://www.libsdl.org/release/SDL2-2.0.14.dmg
          7z x SDL2-2.0.14.dmg
          cd SDL2
          tar -czf ../../out/SDL2-2.0.14.framework.tgz SDL2.framework
        working-directory: scratch
        shell: bash

      - name: SDL2_mixer.framework
        run: |
          wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.dmg
          7z x SDL2_mixer-2.0.4.dmg
          cd SDL2_mixer
          tar -czf ../../out/SDL2_mixer-2.0.4.framework.tgz SDL2_mixer.framework
        working-directory: scratch
        shell: bash

      - name: SDL2 windows runtime
        run: wget https://www.libsdl.org/release/SDL2-2.0.14-win32-x64.zip
        working-directory: out
        shell: bash

      - name: SDL2 mixer windows runtime
        run: wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x64.zip
        working-directory: out
        shell: bash

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ci-artifact
          if-no-files-found: error
          retention-days: 3
          path: |
            out/*.tar.xz
            out/*.tgz
            out/*.zip
